use_frameworks!
platform :ios, '9.3'



target 'LEONetworkLayer_Example' do
  
  pod 'LEONetworkLayer', :path => '../'
  pod 'RxSwift', '~> 4.1.2'
  pod 'RxCocoa', '~> 4.1.2'
  pod 'KeychainSwift', '~> 11.0.0'
  pod 'UIScrollView-InfiniteScroll', '~> 1.1.0'
  
  target 'LEONetworkLayer_Tests' do
    inherit! :search_paths
  end
  
end
