platform :ios, '10.0'

target 'LeoExample' do
  use_frameworks!

  # Project maintenance
  pod 'SwiftGen', '~> 6.1.0'

  # General
  pod 'BaseCoordinator', '~> 1.0'
  pod 'RxCocoa', '~> 4.5.0'

  # Networking
  pod 'LEONetworkLayer', '~> 1.0.0'
# pod 'LEONetworkLayer', :path => '../' 

  # Helpers
  pod 'KeychainSwift', '~> 16.0'

  # UI
  pod 'UIScrollView-InfiniteScroll', '~> 1.1.0'
end
